# Generated by Django 5.2.10 on 2026-02-12 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('tabel_raqami', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Telefon raqami')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'lov qilingan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio_key', models.TextField(blank=True, null=True, verbose_name='Biometrik imzo')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='chat_videos/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='chat_voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('oklad', models.FloatField(default=0)),
                ('norma_soati', models.FloatField(default=0)),
                ('ishlagan_soati', models.FloatField(default=0)),
                ('tungi_soati', models.FloatField(default=0)),
                ('bayram_soati', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userprofile')),
            ],
        ),
    ]
