# Generated by Django 5.2.10 on 2026-02-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
