# Generated by Django 5.2.10 on 2026-02-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_userprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tabel_raqami',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
