# Generated by Django 5.2.10 on 2026-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
